### ISSUE TITLE
feat: hide advanced features on mobile using css classes

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#100]
Related to #99

https://bulma.io/documentation/modifiers/responsive-helpers/#hide

Could potentially be solved by simply using CSS classes to hide it on smaller screens -- on a laptop it is manageable.

**Comment by oysor** [comment]
In SmartNumericInput.tsx, change 
`<div hidden={this.props.hidden} className="field">` 
to 
`const hidden = this.props.hidden ? "is-hidden-touch": ""`
..
`<div className={"field "+hidden}>`
or add a new props-hidden-value to the interface of SmartNumericInput?

**Comment by oysor** [comment]
```
<SmartNumericInputWithLabel
  name="districtThreshold"
..
  label={"%"}
  hidden={"is-hidden-touch"}
/>
```

**Comment by simendag** [comment]
> In SmartNumericInput.tsx, change
> `<div hidden={this.props.hidden} className="field">`
> to
> `const hidden = this.props.hidden ? "is-hidden-touch": ""`
> ..
> `<div className={"field "+hidden}>`
> or add a new props-hidden-value to the interface of SmartNumericInput?

Neither. We may have to rethink this and use state for it after all.

**Comment by simendag** [comment]
@oysor Tedious as it is, we may just have to use a new prop for it. Something like `isHiddenTouch` to mirror what the Bulma code will do. Optional of course, and make sure to put it in the upper-most div and use a check prior to setting the className (ie, build the className with variables and then always render the component the same way).
