### ISSUE TITLE
feat: improve filter readability by using math expressions

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#107]
![image](https://user-images.githubusercontent.com/8669774/76550637-bac99f80-6492-11ea-86b8-7cf4fdb7f521.png)

**Comment by oysor** [comment]
There are only two options, show all (alle med distriktsmandater) or show nothing (ingen data).

What is the point?

**Comment by simendag** [comment]
It is possible to get no district seats, but still get levelling seats.
