### ISSUE TITLE
fix: when the number of district seats is less than 4 they are no longer distributed correctly

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#122]
As the number of district seats is lowered below 4, the sum of district seats is no longer the same as the number of district seats to distribute. 
![S16AI7fxkF](https://user-images.githubusercontent.com/2419963/80301945-598e2f00-87a7-11ea-9df5-9f882440f3f4.gif)

**Comment by Log234** [comment]
The implementation is correct. The problem is that because not every district wins a seat, we can no longer subtract 1 seat (levelling seat) from each district, as some districts ends up with a negative number of district seats. This is not a bug in the implementation, but rather a special case in the data.

By handling this special case we end up diverging from the correct implementation of the algorithm.

One way to handle the case would be to not distribute levelling seats when the sum of district seats and levelling seats are under a certain number, for example 25.

**Comment by Log234** [comment]
I sent an email to Bernt asking how he would suggest that we handle the case.

**Comment by simendag** [comment]
It seems unlikely that one can even _have_ a negative number of seats in any (democratic) electoral system! 😜

**Comment by Log234** [comment]
Indeed, one should never have a negative number of seats but that is currently the result of following the Norwegian electoral system with extreme changes to the input parameters. Of course in the electoral system we can safely assume that it was never intended to have 4 district seats in the parliament.

**Comment by simendag** [comment]
Did we fix the bug involving a similar problem at higher numbers as well? Are we certain it's "4" that causes this?

**Comment by simendag** [comment]
I still don't understand how this implementation can be correct while simultaneously distributing more seats than are available for distribution. Could you reference the file in the current master build where it happens with lines, and show why it's happening but is still correct?

**Comment by Log234** [comment]
The problem is when we distribute the district seats on each district: [utils.ts#L141](https://github.com/Project-Lavinia/Lavinia-client/blob/54b0bc2129e8d2473e339cacb1f1adbc37329555/src/computation/logic/utils.ts#L141)
We distribute the number of district seats + the number of districts (representing the number of levelling seats, a simplification necessary and approved by Bernt): [utils.ts#L142](https://github.com/Project-Lavinia/Lavinia-client/blob/54b0bc2129e8d2473e339cacb1f1adbc37329555/src/computation/logic/utils.ts#L142)
And then we subtract 1 seat (the levelling seat) from each district: [utils.ts#L163](https://github.com/Project-Lavinia/Lavinia-client/blob/54b0bc2129e8d2473e339cacb1f1adbc37329555/src/computation/logic/utils.ts#L163)

The problem arises when the sum of district seats + levelling seats is so low that more than (total seats - levelling seats) districts win 2 seats in the distribution. That means some districts do not receive any seats, so when we subtract 1 levelling seat, they end up at -1 seats. Some districts will end up winning two levelling seats, and since we only subtract one levelling seats from any district, they will end up with an extra seat. That extra seat that some party wins is the reason for why the total number of district seats is not correct, because we only count parties with > 0 seats, leaving out the -1 parties.

**Comment by Log234** [comment]
Bernt confirmed that my suggested approach to this problem was correct. Moving ahead with creating a PR.
