### ISSUE TITLE
feat: ensure that SingleDistrict shows all parties by default

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#124]

**Comment by oysor** [comment]
This function
```
/**
 * Action creator for initializing the presentation.
 */
export function initializePresentation(): InitializePresentation {
    const action: InitializePresentation = {
        type: PresentationMenuActionType.INITIALIZE_PRESENTATION,
        initialPresentation: PresentationType.ElectionTable,
        decimals: "2",
        decimalsNumber: 2,
        showPartiesWithoutSeats: false,
    };
    return action;
}
```
 overides 
```
 export const unloadedState: PresentationMenuState = {
    showComparison: false,
    showFilters: false,
    mergeDistricts: false,
    currentPresentation: PresentationType.ElectionTable,
    decimals: "2",
    decimalsNumber: 2,
    showPartiesWithoutSeats: false,
    districtSelected: "Østfold",
    disproportionalityIndex: DisproportionalityIndex.LOOSEMORE_HANBY,
};
```
So it is sufficient to set `showPartiesWithoutSeats: true` in initializePresentation().

**Comment by simendag** [comment]
But this ensures it's the default for _every view_, not just for SingleDistrict.

**Comment by oysor** [comment]
I don't know if this is the "proper" way to do it. But It works.

In `presentation.menu.actions.ts`
```
export function changePresentation(presentationSelected: PresentationType): ChangePresentation {
    const action: ChangePresentation = {
        type: PresentationMenuActionType.CHANGE_PRESENTATION,
        presentationSelected,
        showPartiesWithoutSeats: presentationSelected == 'TABLE_SINGLE_COUNTY' ? true : false,
    };
    return action;
}
```
In `presentation.menu.reducer.ts`
```
case PresentationMenuActionType.CHANGE_PRESENTATION:
    return {
        ...state,
         currentPresentation: action.presentationSelected,
         showPartiesWithoutSeats: action.showPartiesWithoutSeats,
    };
```

**Comment by simendag** [comment]
`showPartiesWithoutSeats: presentationSelected == 'TABLE_SINGLE_COUNTY' ? true : false,`

Not sure I like this solution -- but regardless there are two mistakes in this line. For one you are using `==` and not `===`, and second, a conditional evaluates to a boolean. The `? true : false` is completely unnecessary.

@Log234 How do you feel about this approach? I am a bit hesitant to modify state with one-off things like this, it seems to couple the action strongly to a single view.

**Comment by Log234** [comment]
Should we not always show all parties by default? I believe that was something requested by Bernt.

**Comment by simendag** [comment]
> Should we not always show all parties by default? I believe that was something requested by Bernt.

It's quite a bit of noise, and I don't think he displays them himself in Celius, but if that's a decision that has been made, we can do it that way (simply initializing it to showing them all).
