### ISSUE TITLE
fix: add %-sign to proportionality columns (in the header)

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#127]
It is currently *very* unclear what proportionality actually is measured in
- [x] Add %-sign to proportionality column in SingleDistrict
- [ ] Add %-sign to proportionality column in DistrictOverview

**Comment by oysor** [comment]
For a party, it is the % of seats minus % of votes. Closer to zero means better proportionality. Positive % means percentage of seats a party won without having votes to back it up. Negative vice versa. Maybe add a hover text to explain it?

**Comment by simendag** [comment]
> For a party, it is the % of seats minus % of votes. Closer to zero means better proportionality. Positive % means percentage of  a party won without having votes to back it up. Negative vice versa. Maybe add a hover text to explain it?

Maybe for the next release. This issue only adds the % for indicating that we are in fact talking about a percentage, and not some arbitrary number.
