### ISSUE TITLE
fix: add %-sign to the right of the input boxes for thresholds

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#128]
An easy method for this is to look at https://bulma.io/documentation/form/input/ and rather than using Font Awesome icons, you simply replace the <i class"whatever"></i> with `<p>%</p>`

**Comment by simendag** [comment]
It is at least an improvement to what we have now, which doesn't indicate that it is a percentage.

**Comment by oysor** [comment]
![sperregrense_med_prosentegn](https://user-images.githubusercontent.com/23212478/80720251-f250e180-8afc-11ea-9c72-d606f448e5db.png)

A solution
```

        const icon = this.props.icon ? <p className="icon is-small is-left has-text-black">%</p> : null;
        const hasIconsLeft = this.props.icon ? "has-icons-left" : "";
```

**Comment by oysor** [comment]
`    const icon = this.props.icon ? 
    <p className="icon is-small is-left has-text-black">{this.props.icon}</p> : null;`

**Comment by simendag** [comment]
@oysor It would be better if you made suggestions in a way I could check, like say, a pull request or a draft pull request where you gather the changes of the "fix"-issues scheduled for the next release. It's hard to tell if this is a good solution without the context of the rest of the code, line numbers, etc.

Immediately I can tell that `this.props.icon` should probably be named differently -- it's a boolean, so something like `showIcon` or `hasIcon` would make more sense (an icon property might actually hold an .svg or an url if it represents an actual icon...).

**Comment by Log234** [comment]
@simendag it's not mine, just looking at his use: `<p className="icon is-small is-left has-text-black">{this.props.icon}</p>`

**Comment by simendag** [comment]
As discussed, you should probably extend that component rather than modifying one that works and is in use several places.

**Comment by Log234** [comment]
@simendag Is the argument that the component becomes too complex by adding an additional optional property?

**Comment by simendag** [comment]
That is one aspect of it. Another is testing. If we modify this component, we have to test every feature related to it when it is changed. If it is a new component, we only have to check that the new component does what we want. Extending the old component lets us keep the behaviour from the last one (which we know works) and add what is needed for the new functionality to the extended component.
