### ISSUE TITLE
fix: seats won by parties below the election threshold should not be distributed in the national distribution

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#136]
Currently, in the national distribution we distribute the total number of seats in the election. This is incorrect, as seats which were won by a party below the election threshold should not contribute to the distribution of levelling seats. Here is a document by the government describing the correct procedure: https://www.stortinget.no/no/Saker-og-publikasjoner/Publikasjoner/Innstillinger/Stortinget/2013-2014/inns-201314-001/7/.

**Comment by simendag** [comment]
Nice catch, how did you find out?

**Comment by Log234** [comment]
> 
> 
> Nice catch, how did you find out?

I've been coming through the code to look for reasons for it to misbehave.

**Comment by Log234** [comment]
Turns out the description we have received from Bernt is incorrect, according to [stortinget](https://www.stortinget.no/no/Saker-og-publikasjoner/Publikasjoner/Innstillinger/Stortinget/2013-2014/inns-201314-001/7/).

I have updated the issue to reflect this change.
