### ISSUE TITLE
style: separate thousands with space

### ISSUE THREAD

**Issue by oysor** [Project-Lavinia/Lavinia-client#141]
Numbers in votes column (in DistrictTable, ElectionTable and SingleDistrict) looks better with space between the thousands. 
160820 -> 160 820

**Comment by simendag** [comment]
This may break sorting algorithms used in React-Table, so I'm not sure how wise it is given the effort involved in rewriting those algorithms / functions to still appropriately sort.

**Comment by oysor** [comment]
One solution is to add Cell:
```
{
  Header: "Stemmer",
  accessor: "votes",
  Footer: (
    <span>
       <strong>{data.map((value) => value.votes).reduce(toSum)}</strong>
    </span>
  ),
  Cell: (row) => {
     return row.value.toString()
     .replace(/\B(?=(\d{3})+(?!\d))/g, " ");
  }
},
```
For a 6 digit number it would take 54 steps to calculate for every row.
https://regex101.com/r/WldKAq/1

Does not seem to break the sorting algorithm.

**Comment by simendag** [comment]
If anything we would be using NumberFormat like described in #142 -- regex should really be a last resort due to how hard it is to maintain and update safely.
