### ISSUE TITLE
fix: navigation menu highlight and drop-down selection has different colours

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#168]
Perhaps the menu highlight and drop-down selection should have the same colour?
![image](https://user-images.githubusercontent.com/2419963/82302329-bef5ca00-99b9-11ea-99b6-7b111592a30e.png)

**Comment by simendag** [comment]
I don't think this is fixable at all without an incredible change to the UI. Closing it and tagging it with future-ui. We could re-work the select boxes (inputs) into something else with divs that will have this behaviour, but it's probably too much work to do with things working as they currently are.
