### ISSUE TITLE
Refactor: remove "Originalt 1.4"  

### ISSUE THREAD

**Issue by oysor** [Project-Lavinia/Lavinia-client#175]
Suggestion from Bernt. Default value 1.4 is obvious.

**Comment by oysor** [comment]
An alternative solution could be to highlight the ResetButton button.

![ResetButton](https://user-images.githubusercontent.com/23212478/83029180-a8dbaf80-a032-11ea-95e3-785ded3b53d3.gif)

**Comment by simendag** [comment]
I don't think this is likely to be removed any time soon; we might reopen/revisit it for a future  re-work of the UI.
