### ISSUE TITLE
style: make SingleDistrict info-box parties indicated

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#190]
The parties should be indicated (bold/underline, something else), and we might want to consider using the full name in the info box rather than the party code (or using abbr to show partyname).

**Comment by oysor** [comment]
Suggestions:

abbreviation tag with partyName
![abbreviation](https://user-images.githubusercontent.com/23212478/85999800-fd48c500-ba0c-11ea-824c-4173595d88a7.png)

only partyName
![only_names](https://user-images.githubusercontent.com/23212478/85999822-03d73c80-ba0d-11ea-86a5-9c42df3c7154.png)

bold
![bold2](https://user-images.githubusercontent.com/23212478/85999853-0b96e100-ba0d-11ea-96e7-94768fd671cf.png)

italic
![italic2](https://user-images.githubusercontent.com/23212478/85999875-12bdef00-ba0d-11ea-8230-1dc082d2a6ba.png)

bold has-text-success
![green](https://user-images.githubusercontent.com/23212478/85999906-1fdade00-ba0d-11ea-9322-a95ae03ae222.png)

italic has-text-success
![italic_green](https://user-images.githubusercontent.com/23212478/85999880-15b8df80-ba0d-11ea-9dbf-c171235cb26b.png)

is-size-4
![big-size-names](https://user-images.githubusercontent.com/23212478/86000559-fd959000-ba0d-11ea-825e-8ae0a9ae2cbc.png)
