### ISSUE TITLE
feat: make limits in ComputationMenu variable depending on election data

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#192]
At present we have set arbitrary percentage maximums for thresholds, but it might be better to "find" the maximum and set that to be the component's max input value, so we don't accidentally obscure possibilities.

**Comment by simendag** [comment]
@Log234 This might be low hanging fruit. We would just need to use the percentage votes of the parties. Not a priority but it would be a nice touch. Maybe use a toast with a list of parties affected by the change of threshold on this basis? Just "thinking out loud" for future reference.

**Comment by Log234** [comment]
We can probably adjust a lot of the limits, I think for the most part it should not break anything on the calculation side of things. I can do some tests tomorrow.

**Comment by Log234** [comment]
This issue is put on hold until we rework the calculation logic of the application.
