### ISSUE TITLE
question: Why does data for parties with no votes at all load in? Is this desirable?

### ISSUE THREAD

**Issue by simendag** [Project-Lavinia/Lavinia-client#193]
![image](https://user-images.githubusercontent.com/8669774/83595827-5551f000-a563-11ea-8bab-56939de78b28.png)

**Comment by Log234** [comment]
It loads data for all parties, because the box for all parties is checked. I feel it would not make sense to hide any parties when the show all parties box is checked, even if they received no votes in that district.

**Comment by simendag** [comment]
This is a bug -- it gives the impression that those parties were part of the election, but as they had no votes, they surely were not.

**Comment by Log234** [comment]
They did receive votes, just not in the district you were looking at:
![image](https://user-images.githubusercontent.com/2419963/89760906-97605a80-daed-11ea-8e86-409f708b7f79.png)

**Comment by simendag** [comment]
Can't we filter these out from the display for SingleDistrict?

**Comment by Log234** [comment]
I think it is less confusing for the user that all parties appear, rather than some mysteriously disappearing for some districts.

**Comment by simendag** [comment]
It's my opinion that it's the equivalent of putting in all the parties of all the elections in every election year. In the scope of a district, only the parties that have been voted for in that district are really relevant, no? Or are there cases where they have 0 votes in the district and still win a district seat there? Potentially the levelling seat(s)?

**Comment by Log234** [comment]
I will argue that there is a distinct difference between participating and being relevant. They should be there out of completeness, rather than because they may win a seat from tweaking settings. There are parties that received less than 25 votes in a district, they won't win any seat pretty much no matter how you tweak the parameters, but they should still be listed.

**Comment by simendag** [comment]
Ones with 25 should be, ones with 0 shouldn't as no votes were cast for them. Again, it's like including every party from every election in case one was missed in my mind. It clutters up the view and gives no benefit.

**Comment by Log234** [comment]
I disagree, including all parties from all elections would be wrong, as they did not participate in that election. However, parties that did participate should be included for historical reasons. Otherwise the party list would be incomplete.

**Comment by simendag** [comment]
One option would be to add filtering to SingleDistrict, and leave those parties out by default to reduce clutter. 

I have never, ever, looked at any of the 0 vote results in SingleDistrict and I doubt anyone else would need or want to either.

It's usually a matter of fringe/tiny parties that have no representation in the district, not major ones one would be confused about being missing.

I really don't understand the insistence on keeping them -- fairly sure my original implementation did this already and it was changed without discussion.

**Comment by simendag** [comment]
A more interesting compromise would be to add another view to display the results of a party in all districts based on a search for the party name or code, giving a "Single Party" view -- where this kind of information would be valid and in scope.

**Comment by Log234** [comment]
Actually, why do we not have filtering of SingleDistrict? It would pretty much be exactly the same filters as Election Overview. Think I could add that fairly quickly.

**Comment by Log234** [comment]
> 
> 
> A more interesting compromise would be to add another view to display the results of a party in all districts based on a search for the party name or code, giving a "Single Party" view -- where this kind of information would be valid and in scope.

Such a view does sound interesting as well... Again, we could reuse the same table. Will have to see how well the data structures line up with the usecase.

**Comment by simendag** [comment]
The view we currently have displaying this kind of data is very messy and borderline useless (early view). It's the one with parties and seats in a huge matrix. I for one think this would be a nice alternative (SingleParty view in the style of the Single District view, perhaps both with filters)

**Comment by Log234** [comment]
I agree, it would be a lot more usable.

**Comment by Log234** [comment]
@simendag Looking at the screenshot again. That must have been from before I removed the common lists (felleslister) from the data. If you check again, there is actually no party that received 0 votes. Or at least not that I can find.

**Comment by simendag** [comment]
Oh we shouldn't filter the districts for a single party. Sort, though, for sure.

It must've been and I just assumed it wasn't fixed. At least we got some good discourse out of it!

I think we should try to get SingleParty working. It'll be very similar to SingleDistrict with lots of reuse.

Maybe filters after that. Will you make issues?

**Comment by Log234** [comment]
Already made issues and started the work.
