### ISSUE TITLE
style: click on Om Lavinia should send the user to the Wiki, not Github

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#203]
The Om Lavinia drop-down should send users to the Wiki, rather than Github.
Instead we should add a Github link in the drop-down.

**Comment by simendag** [comment]
This is already done. I fixed it at some point during 2.8.0 release evaluation I think.

**Comment by simendag** [comment]
Don't we also have another issue like this? https://github.com/Project-Lavinia/Lavinia-client/issues/197

I'm closing this.
