### ISSUE TITLE
Feat: Update tooltipinfo for each presentation type

### ISSUE THREAD

**Issue by oysor** [Project-Lavinia/Lavinia-client#213]
This  one:

![tooltipinfo-table](https://user-images.githubusercontent.com/23212478/89176871-a2196d80-d58a-11ea-8294-472a0f2ac489.png)

**Comment by simendag** [comment]
@oysor Are you working on this? Has it been done?

**Comment by oysor** [comment]
> @oysor Are you working on this? Has it been done?

Nope, not started working on it yet.
