### ISSUE TITLE
feat: get 2021 seat distribution from API and add checkbox for mapping it to previous elections

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#80]
See if it is possible to adjust older elections to match the new distribution from 2020.

**Comment by Log234** [comment]
This is proving to be difficult.
Currently I have managed to create a mapping from the 2020 municipality data to the 2019 districts. The problem is that some districts were split or merged, and because of this there is no data for them individually in SSB. I am unsure how to get the data we need, perhaps I can send an email to SSB or kartverket to hear if they can help us.

**Comment by simendag** [comment]
@Log234 That does seem problematic. I guess we will have to put a hold on this issue until we can find a resolution (probably not in this milestone). I'm moving it to 2.8.

**Comment by Log234** [comment]
@simendag Forgot to comment the issue, but this was resolved. Bernt had the data, and hence I have implemented the necessary changes in both the API and client. These changes are currently pending PRs #143 and [Lavinia-api#31](https://github.com/Project-Lavinia/Lavinia-api/pull/31).
