### ISSUE TITLE
refactor: use AlgorithmType in AlgorithmSelect rather than number tied to enum

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/Lavinia-client#88]
AlgorithmSelect currently handles the algorithm value based on numbers. It would be easier to ensure correct code changes in the future if we used AlgorithmType instead.

**Comment by simendag** [comment]
I think there already exists a utility for mapping the "enum"-values to strings, it's just a matter of implementing it pre-state-update when data loads.
